<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0-windows\Temps\traffic_sign_01.jpg" />
    <Content Include="bin\Debug\net8.0-windows\Temps\traffic_sign_02.jpg" />
    <Content Include="bin\Debug\net8.0-windows\Temps\traffic_sign_03.jpg" />
    <Content Include="bin\Debug\net8.0-windows\Temps\traffic_sign_04.jpg" />
    <Content Include="bin\Debug\net8.0-windows\Temps\traffic_sign_05.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
  </ItemGroup>

</Project>