CREATE TABLE IF NOT EXISTS "MoHinh" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Ten" VARCHAR(200) NOT NULL,
    "MoHinhGoc" VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS "PhienBan" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Ten" VARCHAR(100) NOT NULL,
    "MoTa" VARCHAR(500),
    "DuongDanMH" VARCHAR(500),
    "MoHinhId" INTEGER NOT NULL,
    CONSTRAINT "FK_PhienBan_MoHinh" FOREIGN KEY ("MoHinhId") REFERENCES "MoHinh" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_PhienBan_MoHinhId" ON "PhienBan" ("MoHinhId");

INSERT INTO "MoHinh" ("Id", "Ten", "MoHinhGoc")
VALUES
    (1, 'TrafficSign-YOLO', 'yolov8n.pt'),
    (2, 'TrafficSign-Compact', 'yolov8s.pt')
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "PhienBan" ("Id", "Ten", "MoTa", "DuongDanMH", "MoHinhId")
VALUES
    (101, 'v1.0', 'Baseline model', '/models/trafficsign/v1.0.pt', 1),
    (102, 'v1.1', 'Improved augmentations', '/models/trafficsign/v1.1.pt', 1),
    (103, 'v0.9', 'Lightweight startup version', '/models/compact/v0.9.pt', 2)
ON CONFLICT ("Id") DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('"MoHinh"', 'Id'),
    GREATEST(COALESCE((SELECT MAX("Id") FROM "MoHinh"), 1), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('"PhienBan"', 'Id'),
    GREATEST(COALESCE((SELECT MAX("Id") FROM "PhienBan"), 1), 1),
    true
);
