apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"server5-uploads-pvc","namespace":"server5"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
    volume.kubernetes.io/storage-provisioner: docker.io/hostpath
  creationTimestamp: "2026-04-07T14:32:07Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: server5-uploads-pvc
  namespace: server5
  resourceVersion: "5774"
  uid: 813dbcbd-6556-44bf-a35e-35f671fbace4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: pvc-813dbcbd-6556-44bf-a35e-35f671fbace4
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
