apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"server5-training-artifact-pvc","namespace":"server5"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}}}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
    volume.kubernetes.io/storage-provisioner: docker.io/hostpath
  creationTimestamp: "2026-04-07T14:32:07Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: server5-training-artifact-pvc
  namespace: server5
  resourceVersion: "5780"
  uid: 1811bdba-0f49-46dc-8e1f-48dbd8953f41
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: pvc-1811bdba-0f49-46dc-8e1f-48dbd8953f41
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound
