// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server3.Data;

#nullable disable

namespace Server3.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317022249_AddBatchSize")]
    partial class AddBatchSize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.KhungNhanDang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BienId")
                        .HasColumnType("integer");

                    b.Property<float>("H")
                        .HasColumnType("real");

                    b.Property<int?>("MauId")
                        .HasColumnType("integer");

                    b.Property<float>("W")
                        .HasColumnType("real");

                    b.Property<float>("XCenter")
                        .HasColumnType("real");

                    b.Property<float>("YCenter")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BienId");

                    b.HasIndex("MauId");

                    b.ToTable("KhungNhanDang", (string)null);
                });

            modelBuilder.Entity("Model.LoaiBien", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("LoaiBien", (string)null);
                });

            modelBuilder.Entity("Model.Mau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DoPhanGiai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TapDuLieuId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TapDuLieuId");

                    b.ToTable("Mau", (string)null);
                });

            modelBuilder.Entity("Model.MauHL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MauId")
                        .HasColumnType("integer");

                    b.Property<int?>("ThongTinHLId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MauId");

                    b.HasIndex("ThongTinHLId");

                    b.ToTable("MauHL", (string)null);
                });

            modelBuilder.Entity("Model.MoHinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MoHinhGoc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("MoHinh", (string)null);
                });

            modelBuilder.Entity("Model.PhienBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanMH")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MoHinhId")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MoHinhId");

                    b.ToTable("PhienBan", (string)null);
                });

            modelBuilder.Entity("Model.TapDuLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TapDuLieu", (string)null);
                });

            modelBuilder.Entity("Model.ThongTinHL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BatDauLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Batch")
                        .HasColumnType("integer");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<float>("DoChinhXac")
                        .HasColumnType("real");

                    b.Property<float>("DoNhay")
                        .HasColumnType("real");

                    b.Property<int>("EarlyStoppingPatience")
                        .HasColumnType("integer");

                    b.Property<int>("Epochs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KetThucLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KichThuocAnh")
                        .HasColumnType("integer");

                    b.Property<float>("LearningRate")
                        .HasColumnType("real");

                    b.Property<string>("LoaiThietBi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MoHinhHLId")
                        .HasColumnType("integer");

                    b.Property<string>("Optimizer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PhienBanHLId")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MoHinhHLId");

                    b.HasIndex("PhienBanHLId");

                    b.ToTable("ThongTinHL", (string)null);
                });

            modelBuilder.Entity("Model.KhungNhanDang", b =>
                {
                    b.HasOne("Model.LoaiBien", "Bien")
                        .WithMany()
                        .HasForeignKey("BienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Mau", null)
                        .WithMany("DsBien")
                        .HasForeignKey("MauId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bien");
                });

            modelBuilder.Entity("Model.Mau", b =>
                {
                    b.HasOne("Model.TapDuLieu", null)
                        .WithMany("DsMau")
                        .HasForeignKey("TapDuLieuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.MauHL", b =>
                {
                    b.HasOne("Model.Mau", "ThongTin")
                        .WithMany()
                        .HasForeignKey("MauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.ThongTinHL", null)
                        .WithMany("DsMauHL")
                        .HasForeignKey("ThongTinHLId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ThongTin");
                });

            modelBuilder.Entity("Model.PhienBan", b =>
                {
                    b.HasOne("Model.MoHinh", null)
                        .WithMany("DsPhienBan")
                        .HasForeignKey("MoHinhId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.ThongTinHL", b =>
                {
                    b.HasOne("Model.MoHinh", "MoHinhHL")
                        .WithMany()
                        .HasForeignKey("MoHinhHLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.PhienBan", "PhienBanHL")
                        .WithMany()
                        .HasForeignKey("PhienBanHLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoHinhHL");

                    b.Navigation("PhienBanHL");
                });

            modelBuilder.Entity("Model.Mau", b =>
                {
                    b.Navigation("DsBien");
                });

            modelBuilder.Entity("Model.MoHinh", b =>
                {
                    b.Navigation("DsPhienBan");
                });

            modelBuilder.Entity("Model.TapDuLieu", b =>
                {
                    b.Navigation("DsMau");
                });

            modelBuilder.Entity("Model.ThongTinHL", b =>
                {
                    b.Navigation("DsMauHL");
                });
#pragma warning restore 612, 618
        }
    }
}
