apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-databases
  namespace: server5
data:
  02-create-databases.sql: |
    CREATE DATABASE aimodel_db OWNER server5;
    CREATE DATABASE training_db OWNER server5;
