apiVersion: v1
data:
  APP_STORAGE_UPLOAD_DIR: /data/uploads
  APP_TRAINING_ARTIFACT_AIMODEL_MODEL_DIR: /data/aimodel
  APP_TRAINING_ARTIFACT_AIMODEL_PUBLIC_PREFIX: /models
  APP_TRAINING_ARTIFACT_TEMP_MODEL_DIR: /data/runtime/training/outputs
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  SERVICES_AIMODEL_BASE_URL: http://aimodel-service:8082
  SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PASSWORD: server5pass
  SPRING_RABBITMQ_USERNAME: server5
  TRAINING_MODEL_OUTPUT_DIR: /data/runtime/training/outputs
  TRAINING_RUNTIME_DIR: /app/runtime/training
  TRAINING_UPLOADS_DIR: /data/uploads
kind: ConfigMap
metadata:
  annotations: {}
  name: server5-common-config
  namespace: server5
