server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/aimodel_db
    username: server5
    password: server5pass
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
