<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="bin\Debug\net6.0\models\defaults\" />
    <Folder Include="bin\Debug\net6.0\models\1\" />
    <Folder Include="bin\Debug\net6.0\training\dataset\images\test\" />
    <Folder Include="bin\Debug\net6.0\training\dataset\images\train\" />
    <Folder Include="bin\Debug\net6.0\training\dataset\images\val\" />
    <Folder Include="bin\Debug\net6.0\training\dataset\labels\test\" />
    <Folder Include="bin\Debug\net6.0\training\dataset\labels\train\" />
    <Folder Include="bin\Debug\net6.0\training\dataset\labels\val\" />
    <Folder Include="bin\Debug\net6.0\uploads\" />
  </ItemGroup>

</Project>
