apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"creationTimestamp":null,"name":"server5"},"spec":{},"status":{}}
  creationTimestamp: "2026-04-07T13:29:12Z"
  labels:
    kubernetes.io/metadata.name: server5
  name: server5
  resourceVersion: "620"
  uid: d7737579-584b-47fb-9484-d2a7388549bc
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
