apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: server5-training-artifact-pvc
  namespace: server5
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
