apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  name: server5-postgres-pvc
  namespace: server5
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
