apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"rabbitmq","namespace":"server5"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rabbitmq"}},"template":{"metadata":{"labels":{"app":"rabbitmq"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"server5-rabbitmq-secret"}}],"image":"rabbitmq:3-management","name":"rabbitmq","ports":[{"containerPort":5672},{"containerPort":15672}]}]}}}}
  creationTimestamp: "2026-04-08T03:14:22Z"
  generation: 16
  name: rabbitmq
  namespace: server5
  resourceVersion: "66017"
  uid: 71325dc9-a035-44da-a5b9-913c0e3d7ef4
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: server5-rabbitmq-secret
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        name: rabbitmq
        ports:
        - containerPort: 5672
          protocol: TCP
        - containerPort: 15672
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2026-04-08T03:14:22Z"
    lastUpdateTime: "2026-04-08T03:14:25Z"
    message: ReplicaSet "rabbitmq-fc75f87c6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-04-15T05:31:53Z"
    lastUpdateTime: "2026-04-15T05:31:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 16
