apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: api-gateway
  namespace: server5
spec:
  ports:
  - nodePort: 30081
    port: 8081
    targetPort: 8081
  selector:
    app: api-gateway
  type: NodePort
