apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: training-orchestrator-service
  namespace: server5
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: training-orchestrator-service
