package com.trafficsigndetector.aimodelservice.service;

import com.trafficsigndetector.aimodelservice.entity.MoHinhEntity;
import com.trafficsigndetector.aimodelservice.entity.PhienBanEntity;
import com.trafficsigndetector.aimodelservice.model.CreateVersionRequest;
import com.trafficsigndetector.aimodelservice.model.MoHinh;
import com.trafficsigndetector.aimodelservice.model.PhienBan;
import com.trafficsigndetector.aimodelservice.repository.MoHinhRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

@Service
public class ModelCatalogService {

    private final MoHinhRepository moHinhRepository;

    public ModelCatalogService(MoHinhRepository moHinhRepository) {
        this.moHinhRepository = moHinhRepository;
    }

    @Transactional(readOnly = true)
    public List<MoHinh> getAllModels() {
        List<MoHinhEntity> models = moHinhRepository.findAllByOrderByIdAsc();
        List<MoHinh> list = new ArrayList<>();
        for (MoHinhEntity model : models) {
            list.add(toModelResponse(model));
        }
        return list;
    }

    @Transactional
    public PhienBan createVersion(int moHinhId, CreateVersionRequest payload) {
        MoHinhEntity model = moHinhRepository.findById(moHinhId).orElse(null);
        if (model == null) {
            throw new IllegalArgumentException("Model not found: " + moHinhId);
        }

        String ten = readString(payload == null ? null : payload.ten(), "phien-ban-" + Instant.now().toEpochMilli());
        String moTa = readString(payload == null ? null : payload.moTa(), "Generated by training-orchestrator-service");
        String duongDan = readString(payload == null ? null : payload.duongDanMH(), "/models/mo-hinh-" + moHinhId + "/" + ten + ".pt");

        PhienBanEntity version = new PhienBanEntity();
        version.setTen(ten);
        version.setMoTa(moTa);
        version.setDuongDanMH(duongDan);
        model.addPhienBan(version);

        MoHinhEntity saved = moHinhRepository.save(model);

        PhienBanEntity created = null;
        for (PhienBanEntity item : saved.getDsPhienBan()) {
            if (item.getTen().equals(ten) && item.getDuongDanMH().equals(duongDan)) {
                created = item;
            }
        }

        if (created == null) {
            throw new IllegalStateException("Could not create model version");
        }

        return toVersionResponse(created);
    }

    private MoHinh toModelResponse(MoHinhEntity model) {
        List<PhienBan> versions = new ArrayList<>();
        List<PhienBanEntity> sortedVersions = new ArrayList<>(model.getDsPhienBan());
        sortedVersions.sort(Comparator.comparing(PhienBanEntity::getId, Comparator.nullsLast(Integer::compareTo)).reversed());

        for (PhienBanEntity version : sortedVersions) {
            versions.add(toVersionResponse(version));
        }

        return new MoHinh(
                model.getId(),
                model.getTen(),
                model.getMoHinhGoc(),
                versions
        );
    }

    private PhienBan toVersionResponse(PhienBanEntity version) {
        return new PhienBan(
                version.getId(),
                version.getTen(),
                version.getMoTa(),
                version.getDuongDanMH()
        );
    }

    private String readString(String raw, String fallback) {
        if (raw == null) {
            return fallback;
        }
        String value = raw.trim();
        return value.isEmpty() ? fallback : value;
    }
}

