apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"aimodel-service","namespace":"server5"},"spec":{"ports":[{"port":8082,"targetPort":8082}],"selector":{"app":"aimodel-service"}}}
  creationTimestamp: "2026-04-08T03:22:14Z"
  name: aimodel-service
  namespace: server5
  resourceVersion: "14358"
  uid: 44346a28-ad93-40b5-a1ae-37e17197d360
spec:
  clusterIP: 10.111.88.143
  clusterIPs:
  - 10.111.88.143
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: aimodel-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
