apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"api-gateway","namespace":"server5"},"spec":{"ports":[{"nodePort":30081,"port":8081,"targetPort":8081}],"selector":{"app":"api-gateway"},"type":"NodePort"}}
  creationTimestamp: "2026-04-07T14:28:33Z"
  name: api-gateway
  namespace: server5
  resourceVersion: "17542"
  uid: ca2df11a-85b5-4a26-8a08-27743fbcfd9e
spec:
  clusterIP: 10.103.12.229
  clusterIPs:
  - 10.103.12.229
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: api-gateway
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
