apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"config-server","namespace":"server5"},"spec":{"ports":[{"port":8888,"targetPort":8888}],"selector":{"app":"config-server"}}}
  creationTimestamp: "2026-04-07T14:28:32Z"
  name: config-server
  namespace: server5
  resourceVersion: "5369"
  uid: 1b8841fc-8322-42e7-bf03-8f820122e82b
spec:
  clusterIP: 10.96.196.43
  clusterIPs:
  - 10.96.196.43
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: config-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
