apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"dataset-service","namespace":"server5"},"spec":{"ports":[{"port":8083,"targetPort":8083}],"selector":{"app":"dataset-service"}}}
  creationTimestamp: "2026-04-07T14:28:32Z"
  name: dataset-service
  namespace: server5
  resourceVersion: "5386"
  uid: 5e670bcc-cb01-4465-9bec-ab03763c2a54
spec:
  clusterIP: 10.101.95.75
  clusterIPs:
  - 10.101.95.75
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: dataset-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
