apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"discovery-server","namespace":"server5"},"spec":{"ports":[{"port":8761,"targetPort":8761}],"selector":{"app":"discovery-server"}}}
  creationTimestamp: "2026-04-07T14:28:31Z"
  name: discovery-server
  namespace: server5
  resourceVersion: "5344"
  uid: 6298a4d8-c448-4121-b4bd-78acd51c3d38
spec:
  clusterIP: 10.102.142.37
  clusterIPs:
  - 10.102.142.37
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: discovery-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
