apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"rabbitmq","namespace":"server5"},"spec":{"ports":[{"name":"amqp","port":5672,"targetPort":5672},{"name":"management","port":15672,"targetPort":15672}],"selector":{"app":"rabbitmq"}}}
  creationTimestamp: "2026-04-08T03:14:22Z"
  name: rabbitmq
  namespace: server5
  resourceVersion: "13410"
  uid: f861d593-4bbb-446b-8b9d-c28b84e119e3
spec:
  clusterIP: 10.109.243.105
  clusterIPs:
  - 10.109.243.105
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: management
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
