apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"training-orchestrator-service","namespace":"server5"},"spec":{"ports":[{"port":8090,"targetPort":8090}],"selector":{"app":"training-orchestrator-service"}}}
  creationTimestamp: "2026-04-07T14:28:32Z"
  name: training-orchestrator-service
  namespace: server5
  resourceVersion: "5403"
  uid: 2bae2073-3bdf-4a91-8834-3a04305c7797
spec:
  clusterIP: 10.101.252.71
  clusterIPs:
  - 10.101.252.71
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: training-orchestrator-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
