apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"training-worker-service","namespace":"server5"},"spec":{"ports":[{"port":8091,"targetPort":8091}],"selector":{"app":"training-worker-service"}}}
  creationTimestamp: "2026-04-07T14:28:32Z"
  name: training-worker-service
  namespace: server5
  resourceVersion: "5424"
  uid: 52dac28d-1411-4c77-a9bd-12085293fe00
spec:
  clusterIP: 10.103.89.54
  clusterIPs:
  - 10.103.89.54
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: training-worker-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
